version: '3.9'

# Extend from the main compose file so as to:
#   1) Override to specify a slimmer dockerfile that does NOT include src, mappings, and startup for node in debugging mode.
#   2) Override to specify a command argument that targets an esbuild generated artifact
#   3) Override to eliminate the debug ports.
services:

  sp:
    extends:
      file: docker-compose.yml
      service: sp
    image: ${DOCKER_REGISTRY}/bu-shibboleth-sp
    command: [ "entrypoint.js" ]
    build:
      dockerfile: Dockerfile-slim
      args:
        - TYPESCRIPT_ENTRYPOINT_FILE=EntrypointSp.ts
    ports:
      - '${EXPRESS_PORT:-5000}:${EXPRESS_PORT:-5000}'

  app:
    extends:
      file: docker-compose.yml
      service: app
    image: ${DOCKER_REGISTRY}/bu-shibboleth-app
    command: [ "entrypoint.js" ]
    build:
      dockerfile: Dockerfile-slim
      args:
        - TYPESCRIPT_ENTRYPOINT_FILE=EntrypointApp.ts
    ports: []
 
networks:
  wp-bridge:
    driver: bridge
