
# -----------------------------------------------------------
#                      STAGE 1
# -----------------------------------------------------------
FROM node:slim AS baseline

ENV NODE_ENV development
USER root
WORKDIR /sp

RUN npm install esbuild -g

COPY ./lib/lambda ./lib/lambda/
COPY ./lib/docker/sp ./lib/

# Creating a dummy context.json file - will keep default imports and destructuring working.
RUN mkdir ./context && echo '{ "SHIBBOLETH": { "secret": {} } }' > context/context.json
COPY context/IContext.ts ./context/

# Build the cloudfront origin requests lambda event package
WORKDIR /sp/lib/lambda
RUN npm install --save-dev

# Build an express app that impersonates cloudfront and hosts the origin requests lambda event package 
WORKDIR /sp/lib/sp
RUN npm install

WORKDIR /sp

RUN \
  esbuild ./lib/lambda/FunctionSpOrigin.ts --bundle --platform=node --outfile=sp.js && \
  esbuild ./lib/docker-entrypoint.js --bundle --platform=node --outfile=entrypoint.js
 

# -----------------------------------------------------------
#                      STAGE 2
# -----------------------------------------------------------
FROM node:slim

ENV NODE_ENV development
USER root
WORKDIR /sp

RUN apt update -y && apt upgrade -y && apt install -y curl;

COPY --from=baseline /sp/entrypoint.js /sp/entrypoint.js

CMD [ "node", "entrypoint.js" ]
