version: '3.9'

services:

  # Shibboleth sp in one container targeting "app" in separate container over network bridge
  sp:
    image: ${DOCKER_REGISTRY}/bu-shibboleth-sp-debug 
    command: [ "dist/esm/EntrypointSp.js" ]
    container_name: sp 
    build:
      context: ./
    environment:
      TZ: UTC
      DOMAIN: ${DOMAIN}
      ENTITY_ID: ${ENTITY_ID}
      IDP_CERT: ${IDP_CERT}
      ENTRY_POINT: ${ENTRY_POINT}
      LOGOUT_URL: ${LOGOUT_URL}
      SAML_CERT: ${SAML_CERT}
      SAML_PK: ${SAML_PK}
      APP_AUTHORIZATION: ${APP_AUTHORIZATION}
      APP_LOGIN_HEADER: ${APP_LOGIN_HEADER}
      APP_LOGOUT_HEADER: ${APP_LOGOUT_HEADER}
      DOCKER_APP_HOST: app
      DOCKER_SP_PORT: ${DOCKER_SP_PORT:-5000}
      DOCKER_APP_PORT: ${DOCKER_APP_PORT:-80}
      # DEBUG: 'true'
    ports:
      - '${DOCKER_SP_PORT:-5000}:${DOCKER_SP_PORT:-5000}'
      - '9229:9229'
    networks:
      wp-bridge:

  app: # Use this name for "DOCKER_APP_HOST" environment variables
    image: ${DOCKER_REGISTRY}/bu-shibboleth-app-debug 
    command: [ "dist/esm/EntrypointApp.js" ]
    container_name: app 
    build:
      context: ./
    depends_on:
      - sp
    expose:
      - ${DOCKER_APP_PORT:-80}
    environment:
      DOMAIN: ${DOMAIN}
      TYPESCRIPT_ENTRYPOINT_FILE: EntrypointApp.ts
      APP_APPEND_AUTH_HEADERS: ${APP_APPEND_AUTH_HEADERS:-true}
      APP_AUTHORIZATION: ${APP_AUTHORIZATION}
      APP_LOGIN_HEADER: ${APP_LOGIN_HEADER}
      APP_LOGOUT_HEADER: ${APP_LOGOUT_HEADER}
      DOCKER_APP_HOST: app
      DOCKER_SP_PORT: ${DOCKER_SP_PORT:-5000}
      DOCKER_APP_PORT: ${DOCKER_APP_PORT:-80}
      # DEBUG: 'true'
    ports:
      - '9228:9229'
    networks:
      wp-bridge:
    
 
networks:
  wp-bridge:
    driver: bridge

